// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCivW_4RXP21wLLCngpc4HsNnyok7jG7kA',
    appId: '1:688585480697:web:ef3060dc5b08eb472d0528',
    messagingSenderId: '688585480697',
    projectId: 'flutter-main-app-demo-58563',
    authDomain: 'flutter-main-app-demo-58563.firebaseapp.com',
    databaseURL: 'https://flutter-main-app-demo-58563-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-main-app-demo-58563.firebasestorage.app',
    measurementId: 'G-0JK0366MLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSFDe37x-1KW5fpqqjhlq49USg7p0VDWc',
    appId: '1:688585480697:android:4720745e517d96892d0528',
    messagingSenderId: '688585480697',
    projectId: 'flutter-main-app-demo-58563',
    databaseURL: 'https://flutter-main-app-demo-58563-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-main-app-demo-58563.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJniibPMdS_1DaJBcjcCsMVr8mD96uwfw',
    appId: '1:688585480697:ios:83dafc52e77fe78f2d0528',
    messagingSenderId: '688585480697',
    projectId: 'flutter-main-app-demo-58563',
    databaseURL: 'https://flutter-main-app-demo-58563-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-main-app-demo-58563.firebasestorage.app',
    androidClientId: '688585480697-3kph2jhue40i7h2o23i79iskl03tfj76.apps.googleusercontent.com',
    iosClientId: '688585480697-mii4q6jq9dt0cr12bco5250eum5lfbq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wlfNewFlutterApp',
  );
}
